name: Monitoring

on:
  push:
    branches:
      - main

jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run pre-report
        run: npm run clean:reports

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: ./reports/*